@baseUrl=https://localhost:7407
@apiKey=fhirnexus-test

### Create Appointment Request:
# @name createAppointmentRequest

POST {{baseUrl}}/Appointment
x-api-key: {{apiKey}}
Content-Type: application/fhir+json

{
  "resourceType": "Appointment",
  "status": "proposed",
  "start": "2120-01-01T12:00:00+08:00",
  "end": "2120-01-01T12:30:00+08:00",
  "participant": [
    {
      "actor": {
        "reference": "Patient/testpatient"
      },
      "status": "tentative"
    }
  ],
  "specialty": [
    {
      "coding": [
        {
          "code": "cardio"
        }
      ]
    }
  ]
}


### Get Appointment Request:
@apptId = {{createAppointmentRequest.response.body.$.id}}
# @name getAppointmentRequest
GET {{baseUrl}}/Appointment/{{apptId}}
x-api-key: {{apiKey}}

### Search Appointment By Specialty Request:
# @name searchCancelledAppointmentRequest
GET {{baseUrl}}/Appointment?specialty=cardio
x-api-key: {{apiKey}}

### Update Appointment Request:
# @name updateAppointmentRequest

PUT {{baseUrl}}/Appointment/{{apptId}}
x-api-key: {{apiKey}}
Content-Type: application/fhir+json

{
  "resourceType": "Appointment",
  "id": "{{apptId}}",
  "status": "proposed",
  "start": "2120-01-01T12:00:00+08:00",
  "end": "2120-01-01T12:30:00+08:00",
  "description": "For followup",
  "participant": [
    {
      "actor": {
        "reference": "Patient/testpatient"
      },
      "status": "tentative"
    }
  ]
}


### Cancel Appointment Update Request:
# @name cancelAppointmentUpdateRequest

PUT {{baseUrl}}/Appointment/{{apptId}}
x-api-key: {{apiKey}}
Content-Type: application/fhir+json

{
  "resourceType": "Appointment",
  "id": "{{apptId}}",
  "status": "cancelled",
  "cancelationReason": {
    "coding": [
      {
        "code": "lost-interest",
        "display": "Lost interest"
      }
    ]
  },
  "start": "2120-01-01T12:00:00+08:00",
  "end": "2120-01-01T12:30:00+08:00",
  "description": "For followup",
  "participant": [
    {
      "actor": {
        "reference": "Patient/testpatient"
      },
      "status": "tentative"
    }
  ]
}

### Cancel Appointment Operation Request:
# @name cancelAppointmentOperationRequest

POST {{baseUrl}}/Appointment/{{apptId}}/$cancel
x-api-key: {{apiKey}}
Content-Type: application/fhir+json

{
  "resourceType": "Parameters",
  "parameter": [
    {
      "name": "cancellationReason",
      "valueCodeableConcept": {
        "coding": [
          {
            "code": "lost-interest"
          }
        ]
      }
    }
  ]
}


### Move Appointment Operation Request:
# @name moveAppointmentOperationRequest

POST {{baseUrl}}/Appointment/{{apptId}}/$move-appointment-date
x-api-key: {{apiKey}}
Content-Type: application/fhir+json

{
  "resourceType": "Parameters",
  "parameter": [
    {
      "name": "days-in-future",
      "valueInteger": 5
    }
  ]
}
      
### Search Cancelled Appointment Request:
# @name searchCancelledAppointmentRequest
GET {{baseUrl}}/Appointment?status=cancelled
x-api-key: {{apiKey}}


### Search by Post Cancelled Appointment Request:
# @name searchCancelledAppointmentRequest
POST {{baseUrl}}/Appointment/_search
x-api-key: {{apiKey}}
Content-Type: application/x-www-form-urlencoded

status=cancelled
