@baseUrl=https://localhost:7407
@apiKey=fhirnexus-test

POST {{baseUrl}}/CarePlan
x-api-key: {{apiKey}}
Content-Type: application/fhir+json

{
	"resourceType": "CarePlan",
	"contained": [
		{
			"resourceType": "Patient",
			"id": "patient-id",
			"identifier": [
				{
					"system": "https://synapxe.sg/identifier/nric",
					"value": "S1234567A"
				}
			],
		},
		{
			"resourceType": "Goal",
			"id": "goal-1",
			"lifecycleStatus": "active",
			"description": {
				"coding": [
					{
						"system": "https://synapxe.sg/ValueSet/hsg-health-goal",
						"code": "G1"
					}
				]
			},
			"subject": {
				"reference": "#patient-id"
			},
			"target": [
				{
					"measure": {
						"coding": [
							{
								"system": "https://synapxe.sg/ValueSet/hsg-goal-measure",
								"code": "GM001"
							}
						]
					},
					"detailQuantity": {
						"value": 65.8,
						"system": "http://unitsofmeasure.org",
						"code": "kg"
					}
				},
				{
					"measure": {
						"coding": [
							{
								"system": "https://synapxe.sg/ValueSet/hsg-goal-measure",
								"code": "GM008",
								"display": "Body Weight Progress Milestone"
							}
						]
					},
					"detailQuantity": {
						"value": 60.8,
						"system": "http://unitsofmeasure.org",
						"code": "kg"
					},
					"dueDuration": {
						"value": 1,
						"system": "http://unitsofmeasure.org",
						"code": "mo"
					}
				}
			]
		}
	],
	"status": "active",
	"intent": "plan",
	"subject": {
		"reference": "#patient-id"
	},
	"author": {
		"type": "Organization",
		"identifier": {
			"system": "https://synapxe.sg/identifier/hci-code",
			"value": "a"
		}
	},
	"goal": [
		{
			"reference": "#goal-1"
		}
	]
}

### goal 2

POST {{baseUrl}}/CarePlan
x-api-key: {{apiKey}}
Content-Type: application/fhir+json

{
	"resourceType": "CarePlan",
	"contained": [
		{
			"resourceType": "Patient",
			"id": "patient-id",
			"identifier": [
				{
					"system": "https://synapxe.sg/identifier/nric",
					"value": "S1234567A"
				}
			],
		},
		{
			"resourceType": "Goal",
			"id": "goal-2",
			"lifecycleStatus": "active",
			"description": {
				"coding": [
					{
						"system": "https://synapxe.sg/ValueSet/hsg-health-goal",
						"code": "G2"
					}
				]
			},
			"subject": {
				"reference": "#patient-id"
			},
			"target": [
				{
					"measure": {
						"coding": [
							{
								"system": "https://synapxe.sg/ValueSet/hsg-goal-measure",
								"code": "GM002"
							}
						]
					},
					"dueDate": "2023-04-01"
				},
				{
					"measure": {
						"coding": [
							{
								"system": "https://synapxe.sg/ValueSet/hsg-goal-measure",
								"code": "GM009",
								"display": "Reduce Cigarette"
							}
						]
					},
					"detailQuantity": {
						"value": 5,
						"system": "http://unitsofmeasure.org",
						"code": "{sticks}/d"
					},
					"dueDuration": {
						"value": 1,
						"system": "http://unitsofmeasure.org",
						"code": "mo"
					}
				},
				{
					"measure": {
						"coding": [
							{
								"system": "https://synapxe.sg/ValueSet/hsg-goal-measure",
								"code": "GM010",
								"display": "Not Ready to Quit Smoking"
							}
						]
					},
					"dueDate": "2025-04-01"
				}
			]
		}
	],
	"status": "active",
	"intent": "plan",
	"subject": {
		"reference": "#patient-id"
	},
	"author": {
		"type": "Organization",
		"identifier": {
			"system": "https://synapxe.sg/identifier/hci-code",
			"value": "a"
		}
	},
	"goal": [
		{
			"reference": "#goal-2"
		}
	]
}

### goal 1 and 2
POST {{baseUrl}}/CarePlan
x-api-key: {{apiKey}}
Content-Type: application/fhir+json

{
	"resourceType": "CarePlan",
	"contained": [
		{
			"resourceType": "Patient",
			"id": "patient-id",
			"identifier": [
				{
					"system": "https://synapxe.sg/identifier/nric",
					"value": "S1234567A"
				}
			],
		},
		{
			"resourceType": "Goal",
			"id": "goal-1",
			"lifecycleStatus": "active",
			"description": {
				"coding": [
					{
						"system": "https://synapxe.sg/ValueSet/hsg-health-goal",
						"code": "G1"
					}
				]
			},
			"subject": {
				"reference": "#patient-id"
			},
			"target": [
				{
					"measure": {
						"coding": [
							{
								"system": "https://synapxe.sg/ValueSet/hsg-goal-measure",
								"code": "GM001"
							}
						]
					},
					"detailQuantity": {
						"value": 65.8,
						"system": "http://unitsofmeasure.org",
						"code": "kg"
					}
				},
				{
					"measure": {
						"coding": [
							{
								"system": "https://synapxe.sg/ValueSet/hsg-goal-measure",
								"code": "GM008",
								"display": "Body Weight Progress Milestone"
							}
						]
					},
					"detailQuantity": {
						"value": 60.8,
						"system": "http://unitsofmeasure.org",
						"code": "kg"
					},
					"dueDuration": {
						"value": 1,
						"system": "http://unitsofmeasure.org",
						"code": "mo"
					}
				}
			]
		},
		{
			"resourceType": "Goal",
			"id": "goal-2",
			"lifecycleStatus": "active",
			"description": {
				"coding": [
					{
						"system": "https://synapxe.sg/ValueSet/hsg-health-goal",
						"code": "G2"
					}
				]
			},
			"subject": {
				"reference": "#patient-id"
			},
			"target": [
				{
					"measure": {
						"coding": [
							{
								"system": "https://synapxe.sg/ValueSet/hsg-goal-measure",
								"code": "GM002"
							}
						]
					},
					"dueDate": "2023-04-01"
				},
				{
					"measure": {
						"coding": [
							{
								"system": "https://synapxe.sg/ValueSet/hsg-goal-measure",
								"code": "GM009",
								"display": "Reduce Cigarette"
							}
						]
					},
					"detailQuantity": {
						"value": 5,
						"system": "http://unitsofmeasure.org",
						"code": "{sticks}/d"
					},
					"dueDuration": {
						"value": 1,
						"system": "http://unitsofmeasure.org",
						"code": "mo"
					}
				},
				{
					"measure": {
						"coding": [
							{
								"system": "https://synapxe.sg/ValueSet/hsg-goal-measure",
								"code": "GM010",
								"display": "Not Ready to Quit Smoking"
							}
						]
					},
					"dueDate": "2025-04-01"
				}
			]
		}
	],
	"status": "active",
	"intent": "plan",
	"subject": {
		"reference": "#patient-id"
	},
	"author": {
		"type": "Organization",
		"identifier": {
			"system": "https://synapxe.sg/identifier/hci-code",
			"value": "a"
		}
	},
	"goal": [
		{
			"reference": "#goal-1"
		},
		{
			"reference": "#goal-2"
		}
	]
}

### get health plan

GET {{baseUrl}}/CarePlan/CC1546B6E0BB4105BE99B0AE80219C24
x-api-key: {{apiKey}}

### 
GET {{baseUrl}}/CarePlan?status=active&_total=accurate
x-api-key: {{apiKey}}
