@baseUrl=https://localhost:7407
@apiKey=fhirnexus-test

POST {{baseUrl}}/CarePlan
x-api-key: {{apiKey}}
Content-Type: application/fhir+json

{
	"resourceType": "CarePlan",
	"contained": [
		{
			"resourceType": "Goal",
			"id": "f873f0480edf4e7da98c01be4c05ad91",
			"lifecycleStatus": "active",
			"description": {
				"coding": [
					{
						"system": "https://synapxe.sg/ValueSet/hsg-health-goal",
						"code": "G1"
					}
				]
			},
			"target": [
				{
					"measure": {
						"coding": [
							{
								"system": "https://synapxe.sg/ValueSet/hsg-goal-measure",
								"code": "GM001"
							}
						]
					},
					"detailQuantity": {
						"value": 65.8,
						"system": "http://unitsofmeasure.org",
						"code": "kg"
					}
				},
				{
					"measure": {
						"coding": [
							{
								"system": "https://synapxe.sg/ValueSet/hsg-goal-measure",
								"code": "GM008",
								"display": "Body Weight Progress Milestone"
							}
						]
					},
					"detailQuantity": {
						"value": 60.8,
						"system": "http://unitsofmeasure.org",
						"code": "kg"
					},
					"dueDuration": {
						"value": 1,
						"system": "http://unitsofmeasure.org",
						"code": "mo"
					}
				}
			]
		},
		{
			"resourceType": "Goal",
			"id": "f873f0480edf4e7da98c01be4c05ad92",
			"lifecycleStatus": "active",
			"description": {
				"coding": [
					{
						"system": "https://synapxe.sg/ValueSet/hsg-health-goal",
						"code": "G2"
					}
				]
			},
			"target": [
				{
					"measure": {
						"coding": [
							{
								"system": "https://synapxe.sg/ValueSet/hsg-goal-measure",
								"code": "GM002"
							}
						]
					},
					"dueDate": "2023-04-01"
				},
				{
					"measure": {
						"coding": [
							{
								"system": "https://synapxe.sg/ValueSet/hsg-goal-measure",
								"code": "GM009",
								"display": "Reduce Cigarette"
							}
						]
					},
					"detailQuantity": {
						"value": 5,
						"system": "http://unitsofmeasure.org",
						"code": "{sticks}/d"
					},
					"dueDuration": {
						"value": 1,
						"system": "http://unitsofmeasure.org",
						"code": "mo"
					}
				},
				{
					"measure": {
						"coding": [
							{
								"system": "https://synapxe.sg/ValueSet/hsg-goal-measure",
								"code": "GM010",
								"display": "Not Ready to Quit Smoking"
							}
						]
					},
					"dueDate": "2025-04-01"
				}
			]
		},
		{
			"resourceType": "Goal",
			"id": "f873f0480edf4e7da98c01be4c05ad93",
			"lifecycleStatus": "active",
			"description": {
				"coding": [
					{
						"system": "https://synapxe.sg/ValueSet/hsg-health-goal",
						"code": "G3"
					}
				]
			},
			"target": [
				{
					"measure": {
						"coding": [
							{
								"system": "https://synapxe.sg/ValueSet/hsg-goal-measure",
								"code": "GM003"
							}
						]
					},
					"detailQuantity": {
						"value": 7,
						"system": "http://unitsofmeasure.org",
						"code": "%"
					}
				}
			]
		},
		{
			"resourceType": "Goal",
			"id": "f873f0480edf4e7da98c01be4c05ad94",
			"lifecycleStatus": "active",
			"description": {
				"coding": [
					{
						"system": "https://synapxe.sg/ValueSet/hsg-health-goal",
						"code": "G4"
					}
				]
			},
			"target": [
				{
					"measure": {
						"coding": [
							{
								"system": "https://synapxe.sg/ValueSet/hsg-goal-measure",
								"code": "GM004"
							}
						]
					},
					"detailRatio": {
						"numerator": {
							"value": 130,
							"system": "http://unitsofmeasure.org",
							"code": "mm[Hg]"
						},
						"denominator": {
							"value": 80,
							"system": "http://unitsofmeasure.org",
							"code": "mm[Hg]"
						}
					}
				},
				{
					"measure": {
						"coding": [
							{
								"system": "https://synapxe.sg/ValueSet/hsg-goal-measure",
								"code": "GM005"
							}
						]
					},
					"detailQuantity": {
						"value": 12,
						"system": "http://unitsofmeasure.org",
						"code": "d"
					}
				}
			]
		},
		{
			"resourceType": "Goal",
			"id": "f873f0480edf4e7da98c01be4c05ad95",
			"lifecycleStatus": "active",
			"description": {
				"coding": [
					{
						"system": "https://synapxe.sg/ValueSet/hsg-health-goal",
						"code": "G5"
					}
				]
			},
			"target": [
				{
					"measure": {
						"coding": [
							{
								"system": "https://synapxe.sg/ValueSet/hsg-goal-measure",
								"code": "GM006"
							}
						]
					},
					"detailQuantity": {
						"value": 2.1,
						"system": "http://unitsofmeasure.org",
						"code": "mmol/L"
					}
				}
			]
		},
		{
			"resourceType": "Goal",
			"id": "f873f0480edf4e7da98c01be4c05ad96",
			"lifecycleStatus": "active",
			"description": {
				"coding": [
					{
						"system": "https://synapxe.sg/ValueSet/hsg-health-goal",
						"code": "G6"
					}
				]
			},
			"target": [
				{
					"measure": {
						"coding": [
							{
								"system": "https://synapxe.sg/ValueSet/hsg-goal-measure",
								"code": "PRG001"
							}
						],
						"text": "PRG001 comment"
					}
				},
				{
					"measure": {
						"coding": [
							{
								"system": "https://synapxe.sg/ValueSet/hsg-goal-measure",
								"code": "PRG002"
							}
						],
						"text": "PRG002 comment"
					}
				},
				{
					"measure": {
						"coding": [
							{
								"system": "https://synapxe.sg/ValueSet/hsg-goal-measure",
								"code": "PRG003"
							}
						],
						"text": "PRG003 comment"
					}
				},
				{
					"measure": {
						"coding": [
							{
								"system": "https://synapxe.sg/ValueSet/hsg-goal-measure",
								"code": "OTH001"
							}
						],
						"text": "A"
					}
				}
			]
		},
		{
			"resourceType": "Goal",
			"id": "f873f0480edf4e7da98c01be4c05ad97",
			"lifecycleStatus": "active",
			"description": {
				"coding": [
					{
						"system": "https://synapxe.sg/ValueSet/hsg-health-goal",
						"code": "G7"
					}
				]
			},
			"target": [
				{
					"measure": {
						"coding": [
							{
								"system": "https://synapxe.sg/ValueSet/hsg-goal-measure",
								"code": "ACT001"
							}
						]
					}
				},
				{
					"measure": {
						"coding": [
							{
								"system": "https://synapxe.sg/ValueSet/hsg-goal-measure",
								"code": "ACT002"
							}
						]
					}
				},
				{
					"measure": {
						"coding": [
							{
								"system": "https://synapxe.sg/ValueSet/hsg-goal-measure",
								"code": "ACT003"
							}
						]
					}
				},
				{
					"measure": {
						"coding": [
							{
								"system": "https://synapxe.sg/ValueSet/hsg-goal-measure",
								"code": "OTH001"
							}
						],
						"text": "A"
					}
				}
			]
		},
		{
			"resourceType": "Goal",
			"id": "f873f0480edf4e7da98c01be4c05ad98",
			"lifecycleStatus": "active",
			"description": {
				"coding": [
					{
						"system": "https://synapxe.sg/ValueSet/hsg-health-goal",
						"code": "G8"
					}
				]
			},
			"target": [
				{
					"measure": {
						"coding": [
							{
								"system": "https://synapxe.sg/ValueSet/hsg-goal-measure",
								"code": "GM007"
							}
						],
						"text": "engage in exercise 2 days per week comment"
					},
					"detailQuantity": {
						"value": 2,
						"system": "http://unitsofmeasure.org",
						"code": "wk"
					}
				},
				{
					"measure": {
						"coding": [
							{
								"system": "https://synapxe.sg/ValueSet/hsg-goal-measure",
								"code": "GM011",
								"display": "Aerobic Exercise Steps"
							}
						],
						"text": "Aerobic Exercise Steps comment"
					},
					"detailQuantity": {
						"value": 10000,
						"system": "http://unitsofmeasure.org",
						"code": "{steps}/d"
					}
				},
				{
					"measure": {
						"coding": [
							{
								"system": "https://synapxe.sg/ValueSet/hsg-goal-measure",
								"code": "GM012",
								"display": "Aerobic Exercise Minutes, Intensity and Frequency"
							}
						],
						"text": "Aerobic Exercise Minutes, Intensity and Frequency comment"
					},
					"detailQuantity": {
						"value": 150,
						"system": "http://unitsofmeasure.org",
						"code": "min"
					},
					"dueDuration": {
						"value": 2,
						"system": "http://unitsofmeasure.org",
						"code": "{days}/wk"
					},
					"extension": [
						{
							"url": "https://synapxe.sg/extension/exercise-intensity",
							"valueCodeableConcept": {
								"coding": [
									{
										"system": "https://synapxe.sg/ValueSet/hsg-exercise-intensity",
										"code": "moderate-vigorous"
									}
								]
							}
						}
					]
				},
				{
					"measure": {
						"coding": [
							{
								"system": "https://synapxe.sg/ValueSet/hsg-goal-measure",
								"code": "GM013",
								"display": "Strength Exercise"
							}
						],
						"text": "Strength Exercise comment"
					}
				},
				{
					"measure": {
						"coding": [
							{
								"system": "https://synapxe.sg/ValueSet/hsg-goal-measure",
								"code": "GM014",
								"display": "Balance Exercise"
							}
						],
						"text": "Balance Exercise comment"
					}
				},
				{
					"measure": {
						"coding": [
							{
								"system": "https://synapxe.sg/ValueSet/hsg-goal-measure",
								"code": "GM015",
								"display": "Flexibility Exercise"
							}
						],
						"text": "Flexibility Exercise comment"
					}
				}
			]
		},
		{
			"resourceType": "Condition",
			"id": "f873f0480edf4e7da98c01be4c05ad99",
			"category": [
				{
					"coding": [
						{
							"system": "https://synapxe.sg/ValueSet/hsg-condition-category",
							"code": "patient-condition-tag"
						}
					]
				}
			],
			"code": {
				"coding": [
					{
						"system": "https://synapxe.sg/ValueSet/hsg-condition-tag",
						"code": "DM"
					}
				]
			}
		}
	],
	"status": "active",
	"intent": "plan",
	"category": [
		{
			"coding": [
				{
					"system": "https://synapxe.sg/ValueSet/hsg-care-plan-category",
					"code": "pophealth-plan"
				}
			]
		}
	],
	"subject": {
		"type": "Patient",
		"identifier": {
			"system": "https://synapxe.sg/identifier/nric",
			"value": "S1234567A"
		}
	},
	"period": {
		"start": "2020-04-01T10:30:01+08:00"
	},
	"author": {
		"type": "Organization",
		"identifier": {
			"system": "https://synapxe.sg/identifier/hci-code",
			"value": "a"
		}
	},
	"addresses": [
		{
			"reference": "#f873f0480edf4e7da98c01be4c05ad99"
		}
	],
	"goal": [
		{
			"reference": "#f873f0480edf4e7da98c01be4c05ad91"
		},
		{
			"reference": "#f873f0480edf4e7da98c01be4c05ad92"
		},
		{
			"reference": "#f873f0480edf4e7da98c01be4c05ad93"
		},
		{
			"reference": "#f873f0480edf4e7da98c01be4c05ad94"
		},
		{
			"reference": "#f873f0480edf4e7da98c01be4c05ad95"
		},
		{
			"reference": "#f873f0480edf4e7da98c01be4c05ad96"
		},
		{
			"reference": "#f873f0480edf4e7da98c01be4c05ad97"
		},
		{
			"reference": "#f873f0480edf4e7da98c01be4c05ad98"
		}
	],
	"activity": [
		{
			"detail": {
				"kind": "Appointment",
				"code": {
					"coding": [
						{
							"system": "https://synapxe.sg/ValueSet/hsg-healthplan-activity-type",
							"code": "recommended-next-check-in",
							"display": "Recommended Next Check-in"
						}
					]
				},
				"status": "scheduled",
				"scheduledTiming": {
					"event": [
						"2023-10"
					]
				}
			}
		},
		{
			"outcomeCodeableConcept": [
				{
					"coding": [
						{
							"system": "https://synapxe.sg/ValueSet/hsg-action-plan-category",
							"code": "AP1",
							"display": "Diet"
						}
					]
				}
			],
			"detail": {
				"kind": "ServiceRequest",
				"code": {
					"coding": [
						{
							"system": "https://synapxe.sg/ValueSet/hsg-action-plan-diet-item",
							"code": "DI001",
							"display": "Limit sodium intake"
						}
					]
				},
				"status": "scheduled",
				"description": "Optional comments for limit-sodium-intake"
			}
		},
		{
			"outcomeCodeableConcept": [
				{
					"coding": [
						{
							"system": "https://synapxe.sg/ValueSet/hsg-action-plan-category",
							"code": "AP1",
							"display": "Diet"
						}
					]
				}
			],
			"detail": {
				"kind": "ServiceRequest",
				"code": {
					"coding": [
						{
							"system": "https://synapxe.sg/ValueSet/hsg-action-plan-diet-item",
							"code": "DI002",
							"display": "Limit sugar intake"
						}
					]
				},
				"status": "scheduled",
				"description": "Optional comments for limit-sugar-intake"
			}
		},
		{
			"outcomeCodeableConcept": [
				{
					"coding": [
						{
							"system": "https://synapxe.sg/ValueSet/hsg-action-plan-category",
							"code": "AP1",
							"display": "Diet"
						}
					]
				}
			],
			"detail": {
				"kind": "ServiceRequest",
				"code": {
					"coding": [
						{
							"system": "https://synapxe.sg/ValueSet/hsg-action-plan-diet-item",
							"code": "DI003",
							"display": "Limit saturated fat intake"
						}
					]
				},
				"status": "scheduled",
				"description": "Optional comments for limit-saturated-fat-intake"
			}
		},
		{
			"outcomeCodeableConcept": [
				{
					"coding": [
						{
							"system": "https://synapxe.sg/ValueSet/hsg-action-plan-category",
							"code": "AP1",
							"display": "Diet"
						}
					]
				}
			],
			"detail": {
				"kind": "ServiceRequest",
				"code": {
					"coding": [
						{
							"system": "https://synapxe.sg/ValueSet/hsg-action-plan-diet-item",
							"code": "DI004",
							"display": "Control carbohydrate intake"
						}
					]
				},
				"status": "scheduled",
				"description": "Optional comments for control-carbohydrate-intake"
			}
		},
		{
			"outcomeCodeableConcept": [
				{
					"coding": [
						{
							"system": "https://synapxe.sg/ValueSet/hsg-action-plan-category",
							"code": "AP1",
							"display": "Diet"
						}
					]
				}
			],
			"detail": {
				"kind": "ServiceRequest",
				"code": {
					"coding": [
						{
							"system": "https://synapxe.sg/ValueSet/hsg-action-plan-diet-item",
							"code": "DI005",
							"display": "Control calorie intake"
						}
					]
				},
				"status": "scheduled",
				"description": "Optional comments for control-carlorie-intake"
			}
		},
		{
			"outcomeCodeableConcept": [
				{
					"coding": [
						{
							"system": "https://synapxe.sg/ValueSet/hsg-action-plan-category",
							"code": "AP1",
							"display": "Diet"
						}
					]
				}
			],
			"detail": {
				"kind": "ServiceRequest",
				"code": {
					"coding": [
						{
							"system": "https://synapxe.sg/ValueSet/hsg-action-plan-diet-item",
							"code": "DI006",
							"display": "Have sufficient fibre intake"
						}
					]
				},
				"status": "scheduled",
				"description": "Optional comments for have-sufficient-fibre-intake"
			}
		},
		{
			"outcomeCodeableConcept": [
				{
					"coding": [
						{
							"system": "https://synapxe.sg/ValueSet/hsg-action-plan-category",
							"code": "AP1",
							"display": "Diet"
						}
					]
				}
			],
			"detail": {
				"kind": "ServiceRequest",
				"code": {
					"coding": [
						{
							"system": "https://synapxe.sg/ValueSet/hsg-action-plan-diet-item",
							"code": "DI007",
							"display": "Have sufficient protein intake"
						}
					]
				},
				"status": "scheduled",
				"description": "Optional comments for have-sufficient-protein-intake"
			}
		},
		{
			"outcomeCodeableConcept": [
				{
					"coding": [
						{
							"system": "https://synapxe.sg/ValueSet/hsg-action-plan-category",
							"code": "AP2",
							"display": "Vaccination"
						}
					]
				}
			],
			"detail": {
				"kind": "ServiceRequest",
				"code": {
					"coding": [
						{
							"system": "https://synapxe.sg/ValueSet/hsg-action-plan-vaccination-item",
							"code": "A-INF",
							"display": "Influenza (INF)"
						}
					]
				},
				"status": "scheduled",
				"scheduledTiming": {
					"repeat": {
						"frequency": 1,
						"period": 1,
						"periodUnit": "a"
					}
				},
				"extension": [
					{
						"url": "https://synapxe.sg/extension/dueDate",
						"valueDate": "2025-04-01"
					}
				]
			}
		},
		{
			"outcomeCodeableConcept": [
				{
					"coding": [
						{
							"system": "https://synapxe.sg/ValueSet/hsg-action-plan-category",
							"code": "AP2",
							"display": "Vaccination"
						}
					]
				}
			],
			"detail": {
				"kind": "ServiceRequest",
				"code": {
					"coding": [
						{
							"system": "https://synapxe.sg/ValueSet/hsg-action-plan-vaccination-item",
							"code": "A-PNC",
							"display": "Pneumococcal conjugate vaccine (PCV)"
						}
					]
				},
				"status": "scheduled",
				"extension": [
					{
						"url": "https://synapxe.sg/extension/dueDate",
						"valueDate": "2025-04-01"
					}
				]
			}
		},
		{
			"outcomeCodeableConcept": [
				{
					"coding": [
						{
							"system": "https://synapxe.sg/ValueSet/hsg-action-plan-category",
							"code": "AP2",
							"display": "Vaccination"
						}
					]
				}
			],
			"detail": {
				"kind": "ServiceRequest",
				"code": {
					"coding": [
						{
							"system": "https://synapxe.sg/ValueSet/hsg-action-plan-vaccination-item",
							"code": "A-PPSV",
							"display": "Pneumococcal polysaccharide (PPSV23)"
						}
					]
				},
				"status": "scheduled",
				"extension": [
					{
						"url": "https://synapxe.sg/extension/dueDate",
						"valueDate": "2025-04-01"
					}
				]
			}
		},
		{
			"outcomeCodeableConcept": [
				{
					"coding": [
						{
							"system": "https://synapxe.sg/ValueSet/hsg-action-plan-category",
							"code": "AP2",
							"display": "Vaccination"
						}
					]
				}
			],
			"detail": {
				"kind": "ServiceRequest",
				"code": {
					"coding": [
						{
							"system": "https://synapxe.sg/ValueSet/hsg-action-plan-vaccination-item",
							"code": "A-Tdap",
							"display": "Tetanus, reduced diphtheria & acellular pertussis (Tdap)"
						}
					]
				},
				"status": "scheduled",
				"extension": [
					{
						"url": "https://synapxe.sg/extension/dueDate",
						"valueDate": "2025-04-01"
					}
				]
			}
		},
		{
			"outcomeCodeableConcept": [
				{
					"coding": [
						{
							"system": "https://synapxe.sg/ValueSet/hsg-action-plan-category",
							"code": "AP2",
							"display": "Vaccination"
						}
					]
				}
			],
			"detail": {
				"kind": "ServiceRequest",
				"code": {
					"coding": [
						{
							"system": "https://synapxe.sg/ValueSet/hsg-action-plan-vaccination-item",
							"code": "A-HPV",
							"display": "Human papillomavirus (HPV2 or HPV4)"
						}
					]
				},
				"status": "scheduled",
				"extension": [
					{
						"url": "https://synapxe.sg/extension/dueDate",
						"valueDate": "2025-04-01"
					}
				]
			}
		},
		{
			"outcomeCodeableConcept": [
				{
					"coding": [
						{
							"system": "https://synapxe.sg/ValueSet/hsg-action-plan-category",
							"code": "AP2",
							"display": "Vaccination"
						}
					]
				}
			],
			"detail": {
				"kind": "ServiceRequest",
				"code": {
					"coding": [
						{
							"system": "https://synapxe.sg/ValueSet/hsg-action-plan-vaccination-item",
							"code": "A-HEPB",
							"display": "Hepatitis B (HepB)"
						}
					]
				},
				"status": "scheduled",
				"extension": [
					{
						"url": "https://synapxe.sg/extension/dueDate",
						"valueDate": "2025-04-01"
					}
				]
			}
		},
		{
			"outcomeCodeableConcept": [
				{
					"coding": [
						{
							"system": "https://synapxe.sg/ValueSet/hsg-action-plan-category",
							"code": "AP2",
							"display": "Vaccination"
						}
					]
				}
			],
			"detail": {
				"kind": "ServiceRequest",
				"code": {
					"coding": [
						{
							"system": "https://synapxe.sg/ValueSet/hsg-action-plan-vaccination-item",
							"code": "A-MMR",
							"display": "Measles, mumps & rubella (MMR)"
						}
					]
				},
				"status": "scheduled",
				"extension": [
					{
						"url": "https://synapxe.sg/extension/dueDate",
						"valueDate": "2025-04-01"
					}
				]
			}
		},
		{
			"outcomeCodeableConcept": [
				{
					"coding": [
						{
							"system": "https://synapxe.sg/ValueSet/hsg-action-plan-category",
							"code": "AP2",
							"display": "Vaccination"
						}
					]
				}
			],
			"detail": {
				"kind": "ServiceRequest",
				"code": {
					"coding": [
						{
							"system": "https://synapxe.sg/ValueSet/hsg-action-plan-vaccination-item",
							"code": "A-CPOX",
							"display": "Varicella (VAR)"
						}
					]
				},
				"status": "scheduled",
				"extension": [
					{
						"url": "https://synapxe.sg/extension/dueDate",
						"valueDate": "2025-04-01"
					}
				]
			}
		}
	],
	"note": [
		{
			"text": "Health plan discussion note",
			"extension": [
				{
					"url": "https://synapxe.sg/extension/health-plan-note-type",
					"valueCodeableConcept": {
						"coding": [
							{
								"system": "https://synapxe.sg/ValueSet/hsg-health-plan-note-type",
								"code": "health-plan-discussion-note",
								"display": "Record of Discussion"
							}
						]
					}
				}
			]
		},
		{
			"text": "one thing to start working on today ",
			"extension": [
				{
					"url": "https://synapxe.sg/extension/health-plan-note-type",
					"valueCodeableConcept": {
						"coding": [
							{
								"system": "https://synapxe.sg/ValueSet/hsg-health-plan-note-type",
								"code": "health-plan-one-thing-to-start",
								"display": "One Thing To Start Working On Today"
							}
						]
					}
				}
			]
		}
	]
}