@baseUrl=https://localhost:7407
@apiKey=fhirnexus-test

POST {{baseUrl}}/CarePlan
x-api-key: {{apiKey}}
Content-Type: application/fhir+json

{
	"resourceType": "CarePlan",
	"contained": [
		{
			"resourceType": "Goal",
			"id": "goal-4",
			"lifecycleStatus": "active",
			"description": {
				"coding": [
					{
						"system": "https://synapxe.sg/ValueSet/hsg-health-goal",
						"code": "G4"
					}
				]
			},
			"target": [
				{
					"measure": {
						"coding": [
							{
								"system": "https://synapxe.sg/ValueSet/hsg-goal-measure",
								"code": "GM004"
							}
						]
					},
					"detailRatio": {
						"numerator": {
							"value": 130,
							"system": "http://unitsofmeasure.org",
							"code": "mm[Hg]"
						},
						"denominator": {
							"value": 80,
							"system": "http://unitsofmeasure.org",
							"code": "mm[Hg]"
						}
					}
				},
				{
					"measure": {
						"coding": [
							{
								"system": "https://synapxe.sg/ValueSet/hsg-goal-measure",
								"code": "GM005"
							}
						]
					},
					"detailQuantity": {
						"value": 12,
						"system": "http://unitsofmeasure.org",
						"code": "d"
					}
				}
			]
		}
	],
	"status": "active",
	"intent": "plan",
	"category": [
		{
			"coding": [
				{
					"system": "https://synapxe.sg/ValueSet/hsg-care-plan-category",
					"code": "pophealth-plan"
				}
			]
		}
	],
	"subject": {
		"type": "Patient",
		"identifier": {
			"system": "https://synapxe.sg/identifier/nric",
			"value": "S1234567A"
		}
	},
	"period": {
		"start": "2020-04-01T10:30:01+08:00"
	},
	"author": {
		"type": "Organization",
		"identifier": {
			"system": "https://synapxe.sg/identifier/hci-code",
			"value": "a"
		}
	},
	"goal": [
		{
			"reference": "#goal-4"
		}
	],
	"activity": [
		{
			"detail": {
				"kind": "Appointment",
				"code": {
					"coding": [
						{
							"system": "https://synapxe.sg/ValueSet/hsg-healthplan-activity-type",
							"code": "recommended-next-check-in",
							"display": "Recommended Next Check-in"
						}
					]
				},
				"status": "scheduled",
				"scheduledTiming": {
					"event": [
						"2025-10"
					]
				}
			}
		}
	]
}