@baseUrl=https://localhost:7407
@apiKey=fhirnexus-test

### Create Inventory Request:
# @name createInventoryRequest

POST {{baseUrl}}/Inventory
x-api-key: {{apiKey}}
Content-Type: application/fhir+json

{
  "resourceType": "Inventory",
  "identifier": [
    {
      "use": "usual",
      "type": {
        "text":  "Medical record number",
        "coding": [
          {
            "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
            "code": "MR"
          }
        ]
      },
      "system": "urn:oid:1.2.36.146.595.217.0.1",
      "value": "12345",
      "period": {
        "start": "2001-05-06"
      },
      "assigner": {
        "display": "Acme Healthcare"
      }
    }
  ],
  "sender": {
    "reference": "Practitioner/michel"
  },
  "receiver": {
    "reference": "Practitioner/John"
  },
  "active": true
}


### get
@inventoryId = {{createInventoryRequest.response.body.$.id}}

GET {{baseUrl}}/Inventory/{{inventoryId}}
x-api-key: {{apiKey}}


### update
POST {{baseUrl}}/Inventory/{{inventoryId}}
x-api-key: {{apiKey}}
Content-Type: application/fhir+json

{
  "resourceType": "Inventory",
  "id": "{{inventoryId}}",
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">\n\t\t\t<table>\n\t\t\t\t<tbody>\n\t\t\t\t\t<tr>\n\t\t\t\t\t\t<td>Name</td>\n\t\t\t\t\t\t<td>Peter James \n              <b>Chalmers</b> (&quot;Jim&quot;)\n            </td>\n\t\t\t\t\t</tr>\n\t\t\t\t\t<tr>\n\t\t\t\t\t\t<td>Address</td>\n\t\t\t\t\t\t<td>534 Erewhon, Pleasantville, Vic, 3999</td>\n\t\t\t\t\t</tr>\n\t\t\t\t\t<tr>\n\t\t\t\t\t\t<td>Contacts</td>\n\t\t\t\t\t\t<td>Home: unknown. Work: (03) 5555 6473</td>\n\t\t\t\t\t</tr>\n\t\t\t\t\t<tr>\n\t\t\t\t\t\t<td>Id</td>\n\t\t\t\t\t\t<td>MRN: 12345 (Acme Healthcare)</td>\n\t\t\t\t\t</tr>\n\t\t\t\t</tbody>\n\t\t\t</table>\n\t\t</div>"
  },
  "identifier": [
    {
      "use": "usual",
      "type": {
        "text":  "Medical record number",
        "coding": [
          {
            "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
            "code": "MR"
          }
        ]
      },
      "system": "urn:oid:1.2.36.146.595.217.0.1",
      "value": "12345",
      "period": {
        "start": "2001-05-06"
      },
      "assigner": {
        "display": "Acme Healthcare"
      }
    }
  ],
  "sender": {
    "reference": "Practitioner/amy"
  },
  "receiver": {
    "reference": "Practitioner/Carlisle"
  },
  "active": true
}


### delete
DELETE {{baseUrl}}/Inventory/{{inventoryId}}
x-api-key: {{apiKey}}
